<a href="https://colab.research.google.com/github/fasthill/ML-DL-study-alone/blob/main/5-3%20%ED%8A%B8%EB%A6%AC%EC%9D%98%20%EC%95%99%EC%83%81%EB%B8%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 트리의 앙상블

## 랜덤포레스트

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_validate, cross_val_score
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.inspection import permutation_importance # .feature_importances_ 대체용으로 사용 추천
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [2]:
wine = pd.read_csv('https://bit.ly/wine_csv_data')
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [3]:
data = wine.iloc[:, :3].values
target = wine.iloc[:, -1]

In [4]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [5]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1, )

In [6]:
scores = cross_validate(rf,
                        X= train_input, y=train_target,
                        return_train_score=True,  # 훈련데이터 결과도 리턴
                        cv=5,
                        n_jobs=-1)

In [7]:
scores

{'fit_time': array([0.7804358 , 0.95252395, 0.83144927, 0.83754778, 1.02618647]),
 'score_time': array([0.12573457, 0.12685966, 0.12895346, 0.12193584, 0.12822008]),
 'test_score': array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926]),
 'train_score': array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])}

In [8]:
print('test score : {} \ntrain score: {}'.format(scores['test_score'].mean(), scores['train_score'].mean() ))

test score : 0.8905151032797809 
train score: 0.9973541965122431


In [9]:
scores_v = cross_val_score(rf,
                        X= train_input, y=train_target,
                        cv=5,
                        n_jobs=-1)

In [10]:
scores_v

array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926])

cross_val_score, cross_validate의 차이는 test_score만 공통으로 갖고 있음.

In [11]:
rf.fit(train_input, train_target)
rf.score(test_input, test_target)

0.8892307692307693

In [12]:
rf.feature_importances_

array([0.23167441, 0.50039841, 0.26792718])

OOB(out of bag): 부트스트랩 샘플에 포함되지 않는 샘플. <br> 이것을 검증세트로 이용하여 평가할 수 있음(아래에서 oob_score_True 지정)

In [13]:
rf_oob = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf_oob.fit(train_input, train_target)

RandomForestClassifier(n_jobs=-1, oob_score=True, random_state=42)

In [14]:
rf_oob.oob_score_  #위의 test score와 결과가 비슷함

0.8934000384837406

## 엑스트라트리

부트스트랩 샘플 사용하지 않고 즉 결정트리를 만들때 전체 데이터를 사용 <br> 결정트리에서처럼 불순도 게산하지 않고, random으로 feature를 선정하여 무작위로 분할함. <br> 속도가 빠름 == DecisionTreeClassifier 매개변수 splitter='random'로 선정한 트리와 동일

In [15]:
from sklearn.ensemble import ExtraTreesClassifier

In [16]:
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et,
                        X=train_input, y=train_target,
                        cv=5,
                        return_train_score=True, n_jobs=-1)

In [17]:
print('train score: {} \n test score: {}'.format(scores['train_score'].mean(), scores['test_score'].mean()))

train score: 0.9974503966084433 
 test score: 0.8887848893166506


In [18]:
et.fit(train_input, train_target)
et.feature_importances_

array([0.20183568, 0.52242907, 0.27573525])

## 그레이디언트 부스팅

로지스틱 손실함수, 평균제곱오차 손실함수의 오차를 줄이기 위하여 회귀트리를 계속 추가하여 사용. Learning rate를 조정하여 최저점을 벗어나지 않도록 진행. 최초 max_depth=3을 지정하여 정확도가 떨어지나 계속 회귀트리를 추가하여 끌어 올림.

In [19]:
from sklearn.ensemble import GradientBoostingClassifier

In [20]:
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb,
                        X=train_input, y=train_target,
                        return_train_score=True,
                        n_jobs=-1)

In [21]:
print('train score: {} \n test score: {}'.format(scores['train_score'].mean(), scores['test_score'].mean()))

train score: 0.8881086892152563 
 test score: 0.8720430147331015


In [22]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb,
                        X=train_input, y=train_target,
                        return_train_score=True,
                        n_jobs=-1)

In [23]:
print('train score: {} \n test score: {}'.format(scores['train_score'].mean(), scores['test_score'].mean()))

train score: 0.9464595437171814 
 test score: 0.8780082549788999


In [24]:
gb.fit(train_input, train_target)
gb.feature_importances_

array([0.15872278, 0.68010884, 0.16116839])

In [25]:
gb.score(train_input, train_target)

0.9382335963055609

## 히스토그램 기반 부스팅

255구간으로 나누어 진행. 1개의 빈칸을 준비하고 있는데, 이 곳은 결측치 이상치등을 모아서 진행함. 따라서 결측치 등이 있는 자료를 그대로 사용해도 됨.

In [26]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [27]:
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs=-1)

In [28]:
print('train score: {} \n test score: {}'.format(scores['train_score'].mean(), scores['test_score'].mean()))

train score: 0.9321723946453317 
 test score: 0.8801241948619236


### Permutation Importance <br>
추천하는 feature 중요도 확인 방법

In [29]:
from sklearn.inspection import permutation_importance

In [30]:
hgb = HistGradientBoostingClassifier()
hgb.fit(train_input, train_target)

HistGradientBoostingClassifier()

In [31]:
result = permutation_importance(hgb,
                                X=train_input, y=train_target,
                                n_repeats=10, random_state=42, n_jobs=-1)

In [32]:
result

{'importances': array([[0.08793535, 0.08350972, 0.08908986, 0.08312488, 0.09274581,
         0.08755051, 0.08601116, 0.09601693, 0.09082163, 0.09082163],
        [0.22782374, 0.23590533, 0.23936887, 0.23436598, 0.23725226,
         0.23436598, 0.23359631, 0.23398114, 0.23994612, 0.22724649],
        [0.08581874, 0.08601116, 0.08062344, 0.07504329, 0.08427939,
         0.07792957, 0.07234943, 0.07465846, 0.08139311, 0.08466423]]),
 'importances_mean': array([0.08876275, 0.23438522, 0.08027708]),
 'importances_std': array([0.00382333, 0.00401363, 0.00477012])}

In [33]:
result['importances_mean']

array([0.08876275, 0.23438522, 0.08027708])

In [34]:
result_test = permutation_importance(hgb,
                                X=test_input, y=test_target,
                                n_repeats=10, random_state=42, n_jobs=-1)

In [35]:
result['importances_mean']

array([0.08876275, 0.23438522, 0.08027708])

#### XGBoost

In [36]:
from xgboost import XGBClassifier

xgb = XGBClassifier(tree_method='hist', random_state=42) # 'hist': HistGradientBoostingClassifier와 동일한 결과
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8824322471423747 0.8726214185237284


#### LightGBM

In [37]:
from lightgbm import LGBMClassifier

lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9338079582727165 0.8789710890649293
